name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10 #removed
#  - python=9.15.0 #added
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
 # - pandas=1.2.3
  - jupyterlab=4.0.9
  - pip=23.3.1
  - mlflow=2.1.1 #added
  - pip:
      #- mlflow==2.8.1 removed
      - wandb==0.16.0