channels:
- conda-forge
dependencies:
- python=3.9.19
- pip<=23.3.1
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - importlib-metadata==6.11.0
  - jaraco-context==5.3.0
  - jaraco-functools==4.0.1
  - jaraco-text==3.12.1
  - more-itertools==10.3.0
  - numpy==1.26.4
  - ordered-set==4.1.0
  - packaging==23.2
  - pandas==2.1.3
  - psutil==6.0.0
  - pyyaml==6.0.2
  - scikit-learn==0.24.1
  - scipy==1.13.1
name: mlflow-env
