#name: basic_cleaning
#channels:
#  - conda-forge
#  - defaults
#dependencies:
#  - pandas=1.1.4
#  - pip=20.3.3
#  - mlflow=2.1.1
#  - scikit-learn=0.24.1
#  - matplotlib=3.6.2
#  - pillow=8.1.2
#  - pip:
#      - wandb==0.13.9
name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
 # - python=3.9.15 #added
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3 #removed
 # - pandas-1.2.3
  - mlflow=2.1.1 #added
  - pip=23.3.1
  - scikit-learn=0.24.1 #added
  #- scikit-learn=1.3.2 removed
  - pip:
      #- mlflow==2.8.1 removed
      - wandb==0.16.0